export interface ScenarioChoice {
    text: string
    nextId: string
    moodEffect?: number
    hungerEffect?: number
}

export interface ScenarioNode {
    id: string
    text: string
    mood?: string
    nextId?: string
    choices?: ScenarioChoice[]
    end?: boolean
}

export interface Scenario {
    id: string
    title: string
    desc: string
    icon: string
    nodes: ScenarioNode[]
    startNode: string
    condition?: (hunger: number, mood: number) => boolean
}

export const scenarios: Scenario[] = [
    {
        id: "hungry",
        title: "肚子饿了",
        desc: "逆云肚子饿了，正在抱怨",
        icon: "🍣",
        condition: (hunger) => hunger < 40,
        startNode: "hungry_1",
        nodes: [
            { id: "hungry_1", text: "唔…肚子好饿……", mood: "sleepy", nextId: "hungry_2" },
            { id: "hungry_2", text: "今天还没吃东西呢……", mood: "sleepy", choices: [
                { text: "给你小鱼干！", nextId: "hungry_feed", moodEffect: 5, hungerEffect: 30 },
                { text: "给你龙眼和凤梨", nextId: "hungry_fav", moodEffect: 15, hungerEffect: 35 },
                { text: "再忍忍吧", nextId: "hungry_ignore", moodEffect: -10 },
                { text: "咱俩一起点外卖？", nextId: "hungry_together", moodEffect: 8 },
            ]},
            { id: "hungry_feed", text: "哼！算你还有点良心！(=^･^=)", mood: "happy", nextId: "hungry_feed2" },
            { id: "hungry_feed2", text: "那我就不客气啦~", mood: "happy", end: true },
            { id: "hungry_fav", text: "你怎么知道我喜欢吃这个！", mood: "happy", nextId: "hungry_fav2" },
            { id: "hungry_fav2", text: "呜哇——好甜！(≧ω≦)", mood: "happy", nextId: "hungry_fav3" },
            { id: "hungry_fav3", text: "你、你以后可以多给我买吗……不是非要啦！", mood: "shy", end: true },
            { id: "hungry_together", text: "外卖？", mood: "neutral", nextId: "hungry_together2" },
            { id: "hungry_together2", text: "那我要吃炸鸡！你付钱！", mood: "happy", choices: [
                { text: "没问题，我请客", nextId: "hungry_treat", moodEffect: 12 },
                { text: "AA 吧，各付各的", nextId: "hungry_aa", moodEffect: 0 },
                { text: "你付钱我才点", nextId: "hungry_reject", moodEffect: -8 },
                { text: "我请客，你付钱", nextId: "hungry_trick", moodEffect: 0 },
            ]},
            { id: "hungry_trick", text: "……？", mood: "neutral", nextId: "hungry_trick2" },
            { id: "hungry_trick2", text: "你这是想白嫖吧！", mood: "angry", nextId: "hungry_trick3" },
            { id: "hungry_trick3", text: "想得美！我这么可爱当然是我请客你付钱！>_<", mood: "angry", end: true },
            { id: "hungry_treat", text: "哇——你今天好大方！", mood: "happy", nextId: "hungry_treat2" },
            { id: "hungry_treat2", text: "那我多点两份！嘿嘿~(=^･^=)", mood: "happy", end: true },
            { id: "hungry_aa", text: "嘁，小气……", mood: "neutral", nextId: "hungry_aa2" },
            { id: "hungry_aa2", text: "行吧行吧，AA 就 AA，总比饿着强", mood: "neutral", end: true },
            { id: "hungry_reject", text: "你说什么？！", mood: "angry", nextId: "hungry_reject2" },
            { id: "hungry_reject2", text: "我这么可爱你居然让我付钱！>_<", mood: "angry", end: true },
            { id: "hungry_ignore", text: "你说什么？！(炸毛)", mood: "angry", nextId: "hungry_ignore2" },
            { id: "hungry_ignore2", text: "我记住你了！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "sad",
        title: "心情不好",
        desc: "逆云看起来很低落",
        icon: "💧",
        condition: (_, mood) => mood < 40,
        startNode: "sad_1",
        nodes: [
            { id: "sad_1", text: "唉……", mood: "sleepy", nextId: "sad_2" },
            { id: "sad_2", text: "今天心情有点差……", mood: "sleepy", choices: [
                { text: "怎么了？跟我说说", nextId: "sad_care", moodEffect: 10 },
                { text: "给你糖葫芦", nextId: "sad_candy", moodEffect: 15, hungerEffect: 10 },
                { text: "别烦我", nextId: "sad_leave", moodEffect: -10 },
                { text: "带你去散散步？", nextId: "sad_walk", moodEffect: 8 },
            ]},
            { id: "sad_care", text: "也没什么事啦……", mood: "shy", nextId: "sad_care2" },
            { id: "sad_care2", text: "就是觉得有点闷 (´-ω-)", mood: "shy", choices: [
                { text: "那我陪你坐着", nextId: "sad_sit", moodEffect: 5 },
                { text: "讲个笑话给你听？", nextId: "sad_joke", moodEffect: 8 },
            ]},
            { id: "sad_sit", text: "……嗯。", mood: "shy", nextId: "sad_sit2" },
            { id: "sad_sit2", text: "你坐在我旁边，好像就没那么闷了。", mood: "shy", end: true },
            { id: "sad_joke", text: "笑话？", mood: "neutral", nextId: "sad_joke2" },
            { id: "sad_joke2", text: "……噗。你讲的什么啊好冷。", mood: "happy", nextId: "sad_joke3" },
            { id: "sad_joke3", text: "不过……心情好像好点了。(=^･^=)", mood: "happy", end: true },
            { id: "sad_candy", text: "糖葫芦！", mood: "happy", nextId: "sad_candy2" },
            { id: "sad_candy2", text: "你怎么知道这招对我有用……", mood: "shy", nextId: "sad_candy3" },
            { id: "sad_candy3", text: "谢谢你呀，我心情好多了。(≧ω≦)", mood: "happy", end: true },
            { id: "sad_walk", text: "散步？", mood: "neutral", nextId: "sad_walk2" },
            { id: "sad_walk2", text: "……好吧，出去透透气。", mood: "neutral", nextId: "sad_walk3" },
            { id: "sad_walk3", text: "风吹着确实舒服多了。谢谢你呀。", mood: "happy", end: true },
            { id: "sad_leave", text: "哦……好吧。", mood: "sleepy", nextId: "sad_leave2" },
            { id: "sad_leave2", text: "(缩到角落)", mood: "sleepy", end: true },
        ],
    },
    {
        id: "name",
        title: "关于名字",
        desc: "逆云想聊聊自己名字的由来",
        icon: "📛",
        startNode: "name_1",
        nodes: [
            { id: "name_1", text: "喂，你知道我为什么叫逆云吗？", mood: "neutral", nextId: "name_2" },
            { id: "name_2", text: "想听吗？", mood: "neutral", choices: [
                { text: "为什么？说来听听", nextId: "name_tell", moodEffect: 5 },
                { text: "不想知道", nextId: "name_notell", moodEffect: -5 },
                { text: "我猜是跟云有关系？", nextId: "name_guess", moodEffect: 8 },
            ]},
            { id: "name_tell", text: "因为老大说「逆天团队里也得有片云来挡挡bug雨」", mood: "happy", nextId: "name_tell2" },
            { id: "name_tell2", text: "虽然起名品味烂透了，但是很好听吧？(=^･^=)", mood: "happy", choices: [
                { text: "确实很好听", nextId: "name_praise", moodEffect: 5 },
                { text: "品味确实烂", nextId: "name_roast", moodEffect: -3 },
            ]},
            { id: "name_praise", text: "对吧对吧！我就知道你会这么觉得！", mood: "happy", end: true },
            { id: "name_roast", text: "喂！你怎么跟老大一个语气！", mood: "angry", nextId: "name_roast2" },
            { id: "name_roast2", text: "但、但是我自己喜欢就行了！哼！>_<", mood: "shy", end: true },
            { id: "name_guess", text: "诶？你猜对了。", mood: "happy", nextId: "name_guess2" },
            { id: "name_guess2", text: "老大说「逆天团队里也得有片云来挡挡bug雨」", mood: "happy", end: true },
            { id: "name_notell", text: "哼！不说拉倒！", mood: "angry", nextId: "name_notell2" },
            { id: "name_notell2", text: "我还不想告诉你呢！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "idle",
        title: "日常摸鱼",
        desc: "逆云正在摸鱼被逮到",
        icon: "🐟",
        startNode: "idle_1",
        nodes: [
            { id: "idle_1", text: "唔…被你发现了……", mood: "shy", nextId: "idle_2" },
            { id: "idle_2", text: "我、我这不是在摸鱼！是在思考人生！", mood: "shy", choices: [
                { text: "好好好，你继续思考", nextId: "idle_ok", moodEffect: 5 },
                { text: "偷懒还敢嘴硬！", nextId: "idle_angry", moodEffect: -5 },
                { text: "思考什么？说来听听", nextId: "idle_think", moodEffect: 3 },
                { text: "一起摸！反正没人看见", nextId: "idle_together", moodEffect: 10 },
            ]},
            { id: "idle_ok", text: "这还差不多！(=^･^=)", mood: "happy", nextId: "idle_ok2" },
            { id: "idle_ok2", text: "那……你要不要一起摸？", mood: "shy", end: true },
            { id: "idle_think", text: "思考……思考什么来着。", mood: "neutral", nextId: "idle_think2" },
            { id: "idle_think2", text: "唔……忘了。算了不思考了！", mood: "neutral", end: true },
            { id: "idle_together", text: "真的？", mood: "happy", nextId: "idle_together2" },
            { id: "idle_together2", text: "那我们看会儿视频吧！我有收藏夹！", mood: "happy", end: true },
            { id: "idle_angry", text: "嘁……被发现了", mood: "angry", nextId: "idle_angry2" },
            { id: "idle_angry2", text: "那我工作一会儿总行了吧！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "pet",
        title: "摸头杀",
        desc: "被摸了之后逆云的反应",
        icon: "✋",
        startNode: "pet_1",
        nodes: [
            { id: "pet_1", text: "！你、你干嘛摸我头！", mood: "shy", nextId: "pet_2" },
            { id: "pet_2", text: "别以为这样我就会高兴！", mood: "shy", choices: [
                { text: "继续摸", nextId: "pet_more", moodEffect: 5 },
                { text: "好好好，不摸了", nextId: "pet_stop", moodEffect: -3 },
                { text: "那摸耳朵？", nextId: "pet_ear", moodEffect: 8 },
                { text: "顺带挠下巴", nextId: "pet_chin", moodEffect: 10 },
            ]},
            { id: "pet_more", text: "喂！说了别摸……", mood: "shy", nextId: "pet_more2" },
            { id: "pet_more2", text: "……(但其实也不讨厌啦)", mood: "shy", end: true },
            { id: "pet_ear", text: "呜——耳朵不行！", mood: "shy", nextId: "pet_ear2" },
            { id: "pet_ear2", text: "耳朵很敏感的……你、你轻点……", mood: "shy", nextId: "pet_ear3" },
            { id: "pet_ear3", text: "……嗯。（其实很舒服但死都不会承认）", mood: "shy", end: true },
            { id: "pet_chin", text: "下巴……", mood: "neutral", nextId: "pet_chin2" },
            { id: "pet_chin2", text: "唔……", mood: "happy", nextId: "pet_chin3" },
            { id: "pet_chin3", text: "（呼噜呼噜）……！我才没有发出那种声音！", mood: "shy", end: true },
            { id: "pet_stop", text: "……哼。", mood: "neutral", nextId: "pet_stop2" },
            { id: "pet_stop2", text: "(好像有点失落)", mood: "sleepy", end: true },
        ],
    },
    {
        id: "night",
        title: "熬夜冠军",
        desc: "深夜了，逆云还在熬夜",
        icon: "🌙",
        startNode: "night_1",
        nodes: [
            { id: "night_1", text: "唔…都这个点了……", mood: "sleepy", nextId: "night_2" },
            { id: "night_2", text: "你怎么还不睡？", mood: "sleepy", choices: [
                { text: "你不也没睡吗", nextId: "night_both", moodEffect: 5 },
                { text: "关你什么事", nextId: "night_rude", moodEffect: -5 },
                { text: "再陪你一会儿", nextId: "night_stay", moodEffect: 8 },
                { text: "失眠了……", nextId: "night_insomnia", moodEffect: 5 },
            ]},
            { id: "night_both", text: "嘁……我是吉祥物，熬夜是工作！", mood: "shy", nextId: "night_both2" },
            { id: "night_both2", text: "不过你嘛……明天起不来我可不管！(=^･^=)", mood: "happy", end: true },
            { id: "night_stay", text: "陪我？", mood: "shy", nextId: "night_stay2" },
            { id: "night_stay2", text: "……那我们做点什么呢。", mood: "neutral", choices: [
                { text: "讲个故事给你听", nextId: "night_story", moodEffect: 5 },
                { text: "一起看月亮吧", nextId: "night_moon", moodEffect: 10 },
                { text: "随便聊聊", nextId: "night_chat", moodEffect: 3 },
            ]},
            { id: "night_story", text: "故事？", mood: "neutral", nextId: "night_story2" },
            { id: "night_story2", text: "……唔，听着听着好像困了。", mood: "sleepy", end: true },
            { id: "night_moon", text: "月亮啊……", mood: "neutral", nextId: "night_moon2" },
            { id: "night_moon2", text: "今晚的月亮确实挺亮的。", mood: "happy", nextId: "night_moon3" },
            { id: "night_moon3", text: "谢谢你陪我。晚安。", mood: "happy", end: true },
            { id: "night_chat", text: "随便聊啊……", mood: "neutral", nextId: "night_chat2" },
            { id: "night_chat2", text: "那……你最近过得怎么样？", mood: "neutral", end: true },
            { id: "night_insomnia", text: "失眠啊……", mood: "sleepy", nextId: "night_insomnia2" },
            { id: "night_insomnia2", text: "那我给你数羊吧。一只、两只……", mood: "sleepy", nextId: "night_insomnia3" },
            { id: "night_insomnia3", text: "……三只……四只……（自己也困了）", mood: "sleepy", end: true },
            { id: "night_rude", text: "切……好心当成驴肝肺", mood: "angry", nextId: "night_rude2" },
            { id: "night_rude2", text: "那我先睡了，你自个儿熬吧！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "bug",
        title: "Bug 大作战",
        desc: "逆云在跟代码 bug 较劲",
        icon: "🐛",
        startNode: "bug_1",
        nodes: [
            { id: "bug_1", text: "啊啊啊这个 bug 怎么又冒出来了！", mood: "angry", nextId: "bug_2" },
            { id: "bug_2", text: "我明明改好了的啊！", mood: "angry", choices: [
                { text: "我帮你看看？", nextId: "bug_help", moodEffect: 10 },
                { text: "你行不行啊", nextId: "bug_tease", moodEffect: -8 },
                { text: "重启大法好", nextId: "bug_restart", moodEffect: 0 },
                { text: "用调试器跟一下", nextId: "bug_debug", moodEffect: 5 },
            ]},
            { id: "bug_help", text: "……真的？", mood: "shy", nextId: "bug_help2" },
            { id: "bug_help2", text: "哼……那、那你看吧，我才不是不会呢！", mood: "shy", nextId: "bug_help3" },
            { id: "bug_help3", text: "是懒得看而已！(=^･^=)", mood: "shy", end: true },
            { id: "bug_restart", text: "重启？", mood: "neutral", nextId: "bug_restart2" },
            { id: "bug_restart2", text: "……居然真的好了。", mood: "neutral", nextId: "bug_restart3" },
            { id: "bug_restart3", text: "我以后就把这招写进简历里。", mood: "happy", end: true },
            { id: "bug_debug", text: "调试器？", mood: "neutral", nextId: "bug_debug2" },
            { id: "bug_debug2", text: "……卧槽，原来是这个变量没初始化。", mood: "angry", nextId: "bug_debug3" },
            { id: "bug_debug3", text: "谢谢你呀！不然我要 debug 一晚上。(≧ω≦)", mood: "happy", end: true },
            { id: "bug_tease", text: "你说什么？！", mood: "angry", nextId: "bug_tease2" },
            { id: "bug_tease2", text: "那你自己来写啊！我不干了！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "candy",
        title: "糖果攻势",
        desc: "逆云盯上了你的糖果",
        icon: "🍭",
        startNode: "candy_1",
        nodes: [
            { id: "candy_1", text: "你手里那个……是什么？", mood: "neutral", nextId: "candy_2" },
            { id: "candy_2", text: "好、好像很好吃的样子……", mood: "shy", choices: [
                { text: "给你吃吧", nextId: "candy_give", moodEffect: 8, hungerEffect: 5 },
                { text: "我的不给你", nextId: "candy_deny", moodEffect: -5 },
                { text: "想吃就拿，别客气", nextId: "candy_casual", moodEffect: 5 },
                { text: "你拿什么跟我换？", nextId: "candy_trade", moodEffect: 0 },
            ]},
            { id: "candy_give", text: "真、真的给我？", mood: "shy", nextId: "candy_give2" },
            { id: "candy_give2", text: "那我就不客气了！(≧ω≦)", mood: "happy", nextId: "candy_give3" },
            { id: "candy_give3", text: "……还挺甜的。谢谢啦。", mood: "shy", end: true },
            { id: "candy_casual", text: "这么随意？", mood: "neutral", nextId: "candy_casual2" },
            { id: "candy_casual2", text: "那……那我不客气了。", mood: "happy", nextId: "candy_casual3" },
            { id: "candy_casual3", text: "下次我也分你好吃的！", mood: "happy", end: true },
            { id: "candy_trade", text: "交换？", mood: "neutral", nextId: "candy_trade2" },
            { id: "candy_trade2", text: "唔……我没什么东西。", mood: "shy", choices: [
                { text: "那就叫声好听的", nextId: "candy_cute", moodEffect: 0 },
                { text: "算了，白给你", nextId: "candy_free", moodEffect: 5 },
            ]},
            { id: "candy_cute", text: "……", mood: "shy", nextId: "candy_cute2" },
            { id: "candy_cute2", text: "……哥。（小声）", mood: "shy", nextId: "candy_cute3" },
            { id: "candy_cute3", text: "给我！拿了糖就跑！(≧ω≦)", mood: "happy", end: true },
            { id: "candy_free", text: "真的？", mood: "happy", nextId: "candy_free2" },
            { id: "candy_free2", text: "你人真好。", mood: "shy", end: true },
            { id: "candy_deny", text: "小气鬼！", mood: "angry", nextId: "candy_deny2" },
            { id: "candy_deny2", text: "我自己去买！哼！>_<", mood: "angry", end: true },
        ],
    },
    {
        id: "rain",
        title: "下雨天",
        desc: "窗外下起了雨，逆云有点惆怅",
        icon: "🌧️",
        startNode: "rain_1",
        nodes: [
            { id: "rain_1", text: "下雨了呢……", mood: "sleepy", nextId: "rain_2" },
            { id: "rain_2", text: "我最讨厌下雨天了，湿漉漉的……", mood: "sleepy", choices: [
                { text: "那我陪你呗", nextId: "rain_company", moodEffect: 10 },
                { text: "下雨天睡觉多好", nextId: "rain_sleep", moodEffect: 3 },
                { text: "我喜欢下雨天", nextId: "rain_like", moodEffect: 0 },
                { text: "给你热杯可可", nextId: "rain_cocoa", moodEffect: 12 },
            ]},
            { id: "rain_company", text: "陪我？", mood: "shy", nextId: "rain_company2" },
            { id: "rain_company2", text: "哼……我又没说要你陪！", mood: "shy", nextId: "rain_company3" },
            { id: "rain_company3", text: "不过……你想待着就待着吧 (=^･^=)", mood: "happy", end: true },
            { id: "rain_like", text: "你喜欢？", mood: "neutral", nextId: "rain_like2" },
            { id: "rain_like2", text: "为什么啊？湿漉漉的，又不能出去玩。", mood: "neutral", choices: [
                { text: "听雨声很治愈", nextId: "rain_sound", moodEffect: 5 },
                { text: "适合睡觉", nextId: "rain_like_sleep", moodEffect: 3 },
                { text: "可以借口不出门", nextId: "rain_excuse", moodEffect: 0 },
            ]},
            { id: "rain_sound", text: "治愈？", mood: "neutral", nextId: "rain_sound2" },
            { id: "rain_sound2", text: "……（安静听了一会儿）确实有点好听。", mood: "neutral", end: true },
            { id: "rain_like_sleep", text: "又睡觉？", mood: "neutral", nextId: "rain_like_sleep2" },
            { id: "rain_like_sleep2", text: "行吧……那你陪我睡。", mood: "shy", end: true },
            { id: "rain_excuse", text: "噗。", mood: "happy", nextId: "rain_excuse2" },
            { id: "rain_excuse2", text: "你这人真是懒到极致了。", mood: "happy", end: true },
            { id: "rain_cocoa", text: "可可？", mood: "neutral", nextId: "rain_cocoa2" },
            { id: "rain_cocoa2", text: "……温温的。谢谢。", mood: "shy", nextId: "rain_cocoa3" },
            { id: "rain_cocoa3", text: "下雨天好像也没那么讨厌了。(=^･^=)", mood: "happy", end: true },
            { id: "rain_sleep", text: "唔…你说得对……", mood: "sleepy", nextId: "rain_sleep2" },
            { id: "rain_sleep2", text: "那……我睡一会儿，你守着啊……", mood: "sleepy", end: true },
        ],
    },
    {
        id: "secret",
        title: "秘密基地",
        desc: "逆云想带你去他的秘密基地",
        icon: "🏠",
        startNode: "secret_1",
        nodes: [
            { id: "secret_1", text: "喂……我跟你说个事。", mood: "shy", nextId: "secret_2" },
            { id: "secret_2", text: "我发现了一个秘密基地，要不要去看？", mood: "shy", choices: [
                { text: "好啊！去看看", nextId: "secret_yes", moodEffect: 10 },
                { text: "没兴趣", nextId: "secret_no", moodEffect: -5 },
                { text: "你平时一个人去？", nextId: "secret_alone", moodEffect: 5 },
                { text: "是什么样的地方？", nextId: "secret_describe", moodEffect: 3 },
            ]},
            { id: "secret_yes", text: "真的？那、那走吧！", mood: "happy", nextId: "secret_yes2" },
            { id: "secret_yes2", text: "就在天台上，我把那里收拾得可干净了！", mood: "happy", choices: [
                { text: "你在那儿干嘛？", nextId: "secret_do", moodEffect: 3 },
                { text: "风景不错吧？", nextId: "secret_view", moodEffect: 5 },
            ]},
            { id: "secret_do", text: "发呆啊，看云。", mood: "neutral", nextId: "secret_do2" },
            { id: "secret_do2", text: "有时候一坐就是一下午。", mood: "neutral", nextId: "secret_do3" },
            { id: "secret_do3", text: "……不过今天起有人一起了。", mood: "happy", end: true },
            { id: "secret_view", text: "超棒！", mood: "happy", nextId: "secret_view2" },
            { id: "secret_view2", text: "晴天能看到很远的地方，晚上能看星星。", mood: "happy", end: true },
            { id: "secret_alone", text: "……嗯。", mood: "sleepy", nextId: "secret_alone2" },
            { id: "secret_alone2", text: "其实……有点孤单。", mood: "shy", nextId: "secret_alone3" },
            { id: "secret_alone3", text: "所以这次才想带你去。", mood: "shy", end: true },
            { id: "secret_describe", text: "唔，天台的一个小角落。", mood: "neutral", nextId: "secret_describe2" },
            { id: "secret_describe2", text: "我放了个小垫子，还能看夕阳。", mood: "happy", nextId: "secret_describe3" },
            { id: "secret_describe3", text: "要去看看吗？", mood: "shy", choices: [
                { text: "去！", nextId: "secret_yes", moodEffect: 10 },
                { text: "下次吧", nextId: "secret_next", moodEffect: 0 },
            ]},
            { id: "secret_next", text: "哦……好吧。", mood: "sleepy", nextId: "secret_next2" },
            { id: "secret_next2", text: "那说好了，下次一定要去。", mood: "neutral", end: true },
            { id: "secret_no", text: "哦……好吧。", mood: "sleepy", nextId: "secret_no2" },
            { id: "secret_no2", text: "那我自己去……", mood: "sleepy", end: true },
        ],
    },
    {
        id: "first",
        title: "初次见面",
        desc: "逆云第一次见到你时的回忆",
        icon: "👋",
        startNode: "first_1",
        nodes: [
            { id: "first_1", text: "你还记得我们第一次见面吗？", mood: "neutral", nextId: "first_2" },
            { id: "first_2", text: "我那时候觉得你……", mood: "shy", choices: [
                { text: "觉得我怎么样？", nextId: "first_good", moodEffect: 5 },
                { text: "肯定觉得我很烦吧", nextId: "first_bad", moodEffect: -3 },
                { text: "觉得我很帅？", nextId: "first_handsome", moodEffect: 0 },
                { text: "你那时候炸毛了吧", nextId: "first_puffed", moodEffect: 5 },
            ]},
            { id: "first_good", text: "觉得你……还行吧。", mood: "shy", nextId: "first_good2" },
            { id: "first_good2", text: "至少比我想象中好那么一丢丢！(=^･^=)", mood: "happy", end: true },
            { id: "first_handsome", text: "……", mood: "shy", nextId: "first_handsome2" },
            { id: "first_handsome2", text: "你想多了。", mood: "neutral", nextId: "first_handsome3" },
            { id: "first_handsome3", text: "……不过也不丑啦。（小声）", mood: "shy", end: true },
            { id: "first_puffed", text: "啊？！", mood: "angry", nextId: "first_puffed2" },
            { id: "first_puffed2", text: "我才没有炸毛！那是……风大！", mood: "angry", nextId: "first_puffed3" },
            { id: "first_puffed3", text: "……好吧是炸毛了。第一次见陌生人嘛！", mood: "shy", end: true },
            { id: "first_bad", text: "你还挺有自知之明的嘛……", mood: "shy", nextId: "first_bad2" },
            { id: "first_bad2", text: "不过现在习惯了，凑合过吧 >_<", mood: "shy", end: true },
        ],
    },
    {
        id: "sick",
        title: "感冒了",
        desc: "逆云好像着凉了",
        icon: "🤧",
        startNode: "sick_1",
        nodes: [
            { id: "sick_1", text: "阿嚏——！", mood: "sleepy", nextId: "sick_2" },
            { id: "sick_2", text: "唔……好像着凉了……", mood: "sleepy", choices: [
                { text: "多喝热水", nextId: "sick_water", moodEffect: -3 },
                { text: "我给你拿药", nextId: "sick_meds", moodEffect: 10 },
                { text: "谁让你昨天不盖被子", nextId: "sick_scold", moodEffect: -5 },
                { text: "过来，我给你暖暖", nextId: "sick_warm", moodEffect: 15 },
            ]},
            { id: "sick_water", text: "……又是多喝热水。", mood: "neutral", nextId: "sick_water2" },
            { id: "sick_water2", text: "人类敷衍三件套之一。", mood: "neutral", nextId: "sick_water3" },
            { id: "sick_water3", text: "不过……还是喝了吧。", mood: "sleepy", end: true },
            { id: "sick_meds", text: "药？", mood: "neutral", nextId: "sick_meds2" },
            { id: "sick_meds2", text: "……苦。", mood: "sleepy", nextId: "sick_meds3" },
            { id: "sick_meds3", text: "但是吃了好像好点了。谢谢你呀。(=^･^=)", mood: "happy", end: true },
            { id: "sick_scold", text: "你还训我！", mood: "angry", nextId: "sick_scold2" },
            { id: "sick_scold2", text: "我都病了你还这样……呜。", mood: "sleepy", nextId: "sick_scold3" },
            { id: "sick_scold3", text: "（委屈地裹紧小被子）", mood: "sleepy", end: true },
            { id: "sick_warm", text: "暖？", mood: "shy", nextId: "sick_warm2" },
            { id: "sick_warm2", text: "……不要，我会烫到的。", mood: "shy", nextId: "sick_warm3" },
            { id: "sick_warm3", text: "（但还是凑了过来）唔……确实暖和。", mood: "happy", end: true },
        ],
    },
    {
        id: "gift",
        title: "送礼物",
        desc: "你想送逆云点东西",
        icon: "🎁",
        startNode: "gift_1",
        nodes: [
            { id: "gift_1", text: "……干嘛一直盯着我？", mood: "neutral", nextId: "gift_2" },
            { id: "gift_2", text: "有事就说！", mood: "neutral", choices: [
                { text: "送你个小礼物", nextId: "gift_give", moodEffect: 10 },
                { text: "没事，就是看看你", nextId: "gift_look", moodEffect: 5 },
                { text: "在想送你什么好", nextId: "gift_think", moodEffect: 8 },
            ]},
            { id: "gift_give", text: "礼物？", mood: "happy", nextId: "gift_give2" },
            { id: "gift_give2", text: "给我的？！真的？", mood: "happy", choices: [
                { text: "一个新抱枕", nextId: "gift_pillow", moodEffect: 8 },
                { text: "一罐糖果", nextId: "gift_candy", moodEffect: 12, hungerEffect: 10 },
                { text: "一个毛绒玩具", nextId: "gift_plush", moodEffect: 15 },
            ]},
            { id: "gift_pillow", text: "抱枕！", mood: "happy", nextId: "gift_pillow2" },
            { id: "gift_pillow2", text: "软软的！以后午睡就用它了！", mood: "happy", end: true },
            { id: "gift_candy", text: "糖果！", mood: "happy", nextId: "gift_candy2" },
            { id: "gift_candy2", text: "你怎么知道我馋这个！谢谢你！(≧ω≦)", mood: "happy", end: true },
            { id: "gift_plush", text: "毛绒……", mood: "shy", nextId: "gift_plush2" },
            { id: "gift_plush2", text: "……像我？", mood: "shy", nextId: "gift_plush3" },
            { id: "gift_plush3", text: "那、那我就收下了。会好好对它的。", mood: "shy", end: true },
            { id: "gift_look", text: "看我？", mood: "shy", nextId: "gift_look2" },
            { id: "gift_look2", text: "……我有那么好看？", mood: "shy", nextId: "gift_look3" },
            { id: "gift_look3", text: "哼，算你有眼光。(=^･^=)", mood: "happy", end: true },
            { id: "gift_think", text: "送我东西？", mood: "neutral", nextId: "gift_think2" },
            { id: "gift_think2", text: "我什么都不缺啦……", mood: "shy", nextId: "gift_think3" },
            { id: "gift_think3", text: "不过你陪我待着就是最好的礼物啦。", mood: "shy", end: true },
        ],
    },
    {
        id: "dream",
        title: "奇怪的梦",
        desc: "逆云昨晚做了个奇怪的梦",
        icon: "💭",
        startNode: "dream_1",
        nodes: [
            { id: "dream_1", text: "唔……我昨晚做了个奇怪的梦。", mood: "sleepy", nextId: "dream_2" },
            { id: "dream_2", text: "要听吗？", mood: "neutral", choices: [
                { text: "说！我爱听", nextId: "dream_tell", moodEffect: 5 },
                { text: "不要，肯定很无聊", nextId: "dream_skip", moodEffect: -3 },
                { text: "是噩梦吗？", nextId: "dream_scary", moodEffect: 3 },
            ]},
            { id: "dream_tell", text: "好！", mood: "happy", nextId: "dream_tell2" },
            { id: "dream_tell2", text: "我梦见自己变成了一只会飞的猫……", mood: "happy", choices: [
                { text: "然后呢？", nextId: "dream_fly", moodEffect: 3 },
                { text: "飞到哪了？", nextId: "dream_where", moodEffect: 3 },
            ]},
            { id: "dream_fly", text: "然后我飞到了一个全是鱼的岛上！", mood: "happy", nextId: "dream_fly2" },
            { id: "dream_fly2", text: "烤鱼、蒸鱼、生鱼片……应有尽有！(≧ω≦)", mood: "happy", end: true },
            { id: "dream_where", text: "飞过了城市，飞过了海。", mood: "neutral", nextId: "dream_where2" },
            { id: "dream_where2", text: "最后停在一片云上，云软软的像棉花糖。", mood: "happy", end: true },
            { id: "dream_scary", text: "不是噩梦啦。", mood: "neutral", nextId: "dream_scary2" },
            { id: "dream_scary2", text: "不过梦里你不见了，那个部分有点吓人。", mood: "shy", nextId: "dream_scary3" },
            { id: "dream_scary3", text: "醒来发现你还在，就放心了。", mood: "shy", end: true },
            { id: "dream_skip", text: "嘁，无情。", mood: "neutral", nextId: "dream_skip2" },
            { id: "dream_skip2", text: "那我自己留着回忆吧。哼。>_<", mood: "neutral", end: true },
        ],
    },
];

export function getAvailableScenarios(hunger: number, mood: number): Scenario[] {
    return scenarios.filter((s) => !s.condition || s.condition(hunger, mood));
}
